before_script:
  - apt-get update -y
  - apt-get install -y openssh-client
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts